# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20160319_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_ended',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
    ]
