# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20160319_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_ended',
            field=models.DateField(blank=True, default=datetime.date(2016, 3, 19), null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_started',
            field=models.DateField(default=datetime.date(2016, 3, 19)),
        ),
    ]
