# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20160319_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2016, 3, 19, 20, 48, 18, 140570, tzinfo=utc)),
        ),
    ]
