# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20160319_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
