# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20160319_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='Round 0', max_length=200),
        ),
        migrations.AlterField(
            model_name='matchentry',
            name='team',
            field=models.IntegerField(choices=[(0, 'Solo'), (1, 'Team 1'), (2, 'Team 2'), (3, 'Team 3')], default=0),
        ),
    ]
