# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20160320_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
