# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_auto_20160327_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
