# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_matchentry_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='omega',
            field=models.BooleanField(default=False),
        ),
    ]
