# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/characters')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('teams', models.BooleanField(default=False)),
                ('match_type', models.CharField(default='Stock', max_length=100)),
                ('stage', models.CharField(choices=[(0, '75m'), (1, 'Battlefield'), (2, 'Big Battlefield'), (3, 'Boxing Ring'), (4, 'Bridge of Eldin'), (5, 'Castle Siege'), (6, 'Coliseum'), (7, 'Delfino Plaza'), (8, 'Duck Hunt'), (9, 'Final Destination'), (10, 'Flat Zone X'), (11, 'Gamer'), (12, 'Garden of Hope'), (13, 'Gaur Plains'), (14, 'Halberd'), (15, 'Jungle Hijinxs'), (16, 'Kalos Pokémon League'), (17, 'Kongo Jungle 64'), (18, "Luigi's Mansion"), (19, 'Lylat Cruise'), (20, 'Mario Circuit'), (21, 'Mario Galaxy'), (22, 'Mushroom Kingdom U'), (23, 'Norfair'), (24, 'Onett'), (25, 'Orbital Gate Assault'), (26, 'Pac-Land'), (27, "Palutena's Temple"), (28, 'Pilot Wings'), (29, 'Pokémon Stadium 2'), (30, 'Port Town Aero Dive'), (31, 'Pyrosphere'), (32, 'Skyloft'), (33, 'Skyworld'), (34, 'Smashville'), (35, 'Temple'), (36, 'The Great Cave Offensive'), (37, 'Town and City'), (38, 'Wii Fit Studio'), (39, 'Wily Castle'), (40, 'Windy Hill'), (41, 'Woolly World'), (42, 'Wrecking Crew'), (43, 'Wuhu Island'), (44, "Yoshi's Island")], default=9, max_length=100)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(0, 'Free For All'), (1, 'Team 1'), (2, 'Team 2'), (3, 'Team 3')], default=0)),
                ('kos', models.IntegerField(default=0)),
                ('falls', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Character')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Match')),
            ],
            options={
                'verbose_name': 'Match Entry',
                'verbose_name_plural': 'Match Entries',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/player')),
                ('nickname', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField()),
                ('preliminary', models.BooleanField(default=False)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AddField(
            model_name='matchentry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
