# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_length',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('Stock', 'Stock Match'), ('Time', 'Time Match'), ('Coin', 'Coin Match')], default='Stock', max_length=100),
        ),
    ]
