# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20160319_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.IntegerField(choices=[(0, '75m'), (1, 'Battlefield'), (2, 'Big Battlefield'), (3, 'Boxing Ring'), (4, 'Bridge of Eldin'), (5, 'Castle Siege'), (6, 'Coliseum'), (7, 'Delfino Plaza'), (8, 'Duck Hunt'), (9, 'Final Destination'), (10, 'Flat Zone X'), (11, 'Gamer'), (12, 'Garden of Hope'), (13, 'Gaur Plains'), (14, 'Halberd'), (15, 'Jungle Hijinxs'), (16, 'Kalos Pokémon League'), (17, 'Kongo Jungle 64'), (18, "Luigi's Mansion"), (19, 'Lylat Cruise'), (20, 'Mario Circuit'), (21, 'Mario Galaxy'), (22, 'Mushroom Kingdom U'), (23, 'Norfair'), (24, 'Onett'), (25, 'Orbital Gate Assault'), (26, 'Pac-Land'), (27, "Palutena's Temple"), (28, 'Pilot Wings'), (29, 'Pokémon Stadium 2'), (30, 'Port Town Aero Dive'), (31, 'Pyrosphere'), (32, 'Skyloft'), (33, 'Skyworld'), (34, 'Smashville'), (35, 'Temple'), (36, 'The Great Cave Offensive'), (37, 'Town and City'), (38, 'Wii Fit Studio'), (39, 'Wily Castle'), (40, 'Windy Hill'), (41, 'Woolly World'), (42, 'Wrecking Crew'), (43, 'Wuhu Island'), (44, "Yoshi's Island")], default=9),
        ),
    ]
