# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_auto_20160321_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='falls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='kos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('75m', '75m'), ('Battlefield', 'Battlefield'), ('Big Battlefield', 'Big Battlefield'), ('Boxing Ring', 'Boxing Ring'), ('Bridge of Eldin', 'Bridge of Eldin'), ('Castle Siege', 'Castle Siege'), ('Coliseum', 'Coliseum'), ('Delfino Plaza', 'Delfino Plaza'), ('Duck Hunt', 'Duck Hunt'), ('Final Destination', 'Final Destination'), ('Flat Zone X', 'Flat Zone X'), ('Gamer', 'Gamer'), ('Garden of Hope', 'Garden of Hope'), ('Gaur Plains', 'Gaur Plains'), ('Halberd', 'Halberd'), ('Jungle Hijinxs', 'Jungle Hijinxs'), ('Kalos Pokemon League', 'Kalos Pokemon League'), ('Kongo Jungle 64', 'Kongo Jungle 64'), ("Luigi's Mansion", "Luigi's Mansion"), ('Lylat Cruise', 'Lylat Cruise'), ('Mario Circuit', 'Mario Circuit'), ('Mario Galaxy', 'Mario Galaxy'), ('Mushroom Kingdom U', 'Mushroom Kingdom U'), ('Norfair', 'Norfair'), ('Onett', 'Onett'), ('Orbital Gate Assault', 'Orbital Gate Assault'), ('Pac-Land', 'Pac-Land'), ("Palutena's Temple", "Palutena's Temple"), ('Pilot Wings', 'Pilot Wings'), ('Pokemon Stadium 2', 'Pokemon Stadium 2'), ('Port Town Aero Dive', 'Port Town Aero Dive'), ('Pyrosphere', 'Pyrosphere'), ('Skyloft', 'Skyloft'), ('Skyworld', 'Skyworld'), ('Smashville', 'Smashville'), ('Temple', 'Temple'), ('The Great Cave Offensive', 'The Great Cave Offensive'), ('Town and City', 'Town and City'), ('Wii Fit Studio', 'Wii Fit Studio'), ('Wily Castle', 'Wily Castle'), ('Windy Hill', 'Windy Hill'), ('Woolly World', 'Woolly World'), ('Wrecking Crew', 'Wrecking Crew'), ('Wuhu Island', 'Wuhu Island'), ("Yoshi's Island", "Yoshi's Island")], default='Final Destination', max_length=100),
        ),
    ]
